### ISSUE TITLE
_logImpl error on theblog repo

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#131]
Try to open https://theblog--davidnuescheler.hlx.page/posts/creating-adobe-experience-platform-pipeline-with-kafka.html
You get a 500 error.

A quick tracing reveals the follow error:

```
$  wsk activation logs 9bd431b4303a42369431b4303a423687
2019-12-17T14:50:57.840Z       stderr: debug Constructing HTML Pipeline
2019-12-17T14:50:57.841Z       stderr: debug Running HTML pipeline
2019-12-17T14:50:57.842Z       stderr: trying to load https://raw.githubusercontent.com/davidnuescheler/theblog/1cd6616c3638cb6c007f649d2d2482fda4be9e3a/fstab.json
2019-12-17T14:50:58.020Z       stderr: resourcePath=/posts/creating-adobe-experience-platform-pipeline-with-kafka
2019-12-17T14:50:58.020Z       stderr: relPath=/posts/creating-adobe-experience-platform-pipeline-with-kafka
2019-12-17T14:50:58.021Z       stderr: fetching Markdown from https://adobeioruntime.net/api/v1/web/helix/helix-services/word2md@latest?rid=2W0bGtNESm8ETv0aWZyVGht3ci6X79w4&src=davidnuescheler%2Ftheblog%2F1cd6616c3638cb6c007f649d2d2482fda4be9e3a&path=%2Fposts%2Fcreating-adobe-experience-platform-pipeline-with-kafka.docx&shareLink=https%3A%2F%2Fadobe.sharepoint.com%2Fsites%2FTheBlog%2FShared%2520Documents%2Ftheblog%3Fcsf%3D1%26e%3D8Znxth
2019-12-17T14:51:01.554Z       stderr: [ERROR] Exception during #04/use:find from /nodejsAction/XXchKBna/html.js:163608:
TypeError: Cannot read property '_logImpl' of undefined
    at debug (/nodejsAction/XXchKBna/html.js:7069:19)
    at embed (/nodejsAction/XXchKBna/html.js:226419:5)
    at map (/nodejsAction/XXchKBna/html.js:226443:7)
    at preorder (/nodejsAction/XXchKBna/html.js:226480:30)
    at bound (/nodejsAction/XXchKBna/html.js:226489:14)
    at Array.map (<anonymous>)
    at preorder (/nodejsAction/XXchKBna/html.js:226483:35)
    at map (/nodejsAction/XXchKBna/html.js:226476:10)
    at find (/nodejsAction/XXchKBna/html.js:226437:3)
    at execFns (/nodejsAction/XXchKBna/html.js:8431:17)
```

@koraa @tripodsan This seems to be logger related... any idea? 

cc @dominique-pfister

**Comment by tripodsan** [comment]
I think I know what it is.... I think the winston logger used to bind the method to itself, where as helix-log doesn't.

so:

```
const { info } = logger;
info(...)
```
fails. I'll fix it on helix-pages.

**Comment by tripodsan** [comment]
it seems to use an old pipeline. if I execute the action locally, it works.

**Comment by tripodsan** [comment]
ha...no..it's the other way around, using the latest pipeline fails :-)

**Comment by tripodsan** [comment]
fixed with new pipeline that uses new openwhisk-action-logger.
see https://github.com/adobe/openwhisk-action-logger/commit/524029107cae7574e340b37075f464bd6c93a8e7
