### ISSUE TITLE
the fstab loading doesn't work with the new pipeline

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#173]
```
2020-03-02T05:30:12.323Z       stderr: [ERROR] Exception during #01/use:fetchExternal from /nodejsAction/XXcBPldl/html.js:209481:
Error: /schemas/fstab.schema.json: ENOENT: no such file or directory, open '/schemas/fstab.schema.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Object.readFileSync (/nodejsAction/XXcBPldl/html.js:46650:22)
    at MountConfig.init (/nodejsAction/XXcBPldl/html.js:47243:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-pipeline/issues/603
