### ISSUE TITLE
https://not-slides-trieloff.project-helix.page/bend.html throws 500

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pages#83]
Worked just fine yesterday, I expect some Markdown parsing issue to be at the source of it.

**Comment by tripodsan** [comment]
here's the error from `wsk activation get afef9cfd5a4a48d1af9cfd5a4a98d174`:

```
        "result": {
            "body": "<html><body><h1>500</h1><pre>TypeError: Expected input to be a string</pre></body></html>",
            "errorMessage": "TypeError: Expected input to be a string",
            "errorStack": "TypeError: Expected input to be a string\n    at Function.picomatch.test (/nodejsAction/XXIBdiJp/html.js:309814:11)\n    at matcher (/nodejsAction/XXIBdiJp/html.js:309762:48)\n    at items.some.item (/nodejsAction/XXIBdiJp/html.js:307984:28)\n    at Array.some (<anonymous>)\n    at Function.micromatch.some (/nodejsAction/XXIBdiJp/html.js:307984:15)\n    at embed (/nodejsAction/XXIBdiJp/html.js:307663:10)\n    at map (/nodejsAction/XXIBdiJp/html.js:307694:7)\n    at preorder (/nodejsAction/XXIBdiJp/html.js:269833:30)\n    at bound (/nodejsAction/XXIBdiJp/html.js:269842:14)\n    at Array.map (<anonymous>)",
            "headers": {
                "Content-Type": "text/html"
            },
            "statusCode": 500
        }
```

**Comment by trieloff** [comment]
thx.
